CC	 	= armv5te-cross-linux-gnueabi-gcc
CFLAGS  ?= -Wall -fPIC -O2 $(OPTS) $(INCLUDE) $(DEFINES)
LDFLAGS ?= -s -lpthread -ldl -lm -lrt -L. 

OBJ			= bin/arm
EXECUTABLE	= bin/mdnssd-arm

include Makefile

